name: Generate Snake

on:
  schedule: # Gera automaticamente uma vez por dia
    - cron: "0 0 * * *"
  workflow_dispatch: # Permite rodar manualmente
  push: # Roda sempre que você fizer commit

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gera a cobrinha de contribuições
        uses: Platane/snk@v3
        with:
          github_user_name: kemillysantos-lab
          outputs: dist/github-contribution-grid-snake.svg

      - name: Envia o arquivo para o branch "output"
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}